name: gw_matched_filtering_demo
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scipy
  - h5py >=3.3.0
  - matplotlib
  - rise  # For presentations from Jupyter notebooks
  - ipywidgets  # For interactive sliders and such
  - pip
  - pip:
    - gw-matched-filtering-demo
