#! /bin/sh

boyleHOME='/home/PostDocs/mboyle'
localHOME='/home.local/workshopguest'
export PATH=${boyleHOME}/anaconda3/bin:$PATH

echo "Copying required files to local disk"
cp -r ${boyleHOME}/.continuum .
mkdir -p ${localHOME}/MatchedFiltering
cp -r ${boyleHOME}/MatchedFiltering/Data ${localHOME}/MatchedFiltering/
cp -r ${boyleHOME}/MatchedFiltering/Utils ${localHOME}/MatchedFiltering/
cp ${boyleHOME}/MatchedFiltering/MatchedFiltering.ipynb ${localHOME}/MatchedFiltering/
cp ${boyleHOME}/MatchedFiltering/utilities.py ${localHOME}/MatchedFiltering/
cp ${boyleHOME}/MatchedFiltering/70sEqualizer.jpg ${localHOME}/MatchedFiltering/
cp ${boyleHOME}/MatchedFiltering/SearchData/`hostname`.dat ${localHOME}/MatchedFiltering/Data/UnknownData.dat
echo "Finished copying; starting ipython"
echo
cd ${localHOME}/MatchedFiltering
ipython notebook MatchedFiltering.ipynb

/bin/rm -rf ${localHOME}/MatchedFiltering
/bin/rm -rf ${localHOME}/.continuum
